Added bash completion for --filter & --format
buildtesters/buildtest pull request #1242
Opened 2022-09-19 19:12 UTC by prathmesh4321

2022-09-19 19:14 UTC, prathmesh4321 commented
Bash completion for --format and --filter options
![image](https://user-images.githubusercontent.com/35829130/191097151-dfabb415-187b-4aed-bcea-0a8d9fda3121.png)

2022-09-19 21:40 UTC, shahzebsiddiqui commented on bash_completion.sh
> +             local opts="type executor tags buildspec"
please create a bash method that will call the following

```
(buildtest)  ~/Documents/github/buildtest/ [devel] buildtest buildspec find --filterfields
type
executor
tags
buildspec
```

2022-09-19 21:41 UTC, shahzebsiddiqui commented on bash_completion.sh
> +             local opts="name type executor tags description buildspec"
same thing here call a method say `buildspec_format_fields` or whatever.

```
(buildtest)  ~/Documents/github/buildtest/ [devel] buildtest buildspec find --formatfields
name
type
executor
tags
description
buildspec
```

2022-09-19 21:45 UTC, shahzebsiddiqui requested changes
please dont hardcode these bash completion we should be using the builtin commands to get the output.

2022-09-20 19:02 UTC, prathmesh4321 commented on bash_completion.sh
> +             local opts="name type executor tags description buildspec"
Done ! @shahzebsiddiqui

2022-09-21 19:52 UTC, shahzebsiddiqui approved these changes
thanks @prathmesh4321 this looks good

2022-09-21 19:52 UTC, merged