Colorize output for all terse formats
buildtesters/buildtest pull request #1292
Opened 2022-11-04 03:19 UTC by prathmesh4321

Added color for terse option of  **buildtest buildspec maintainers --list** **buildtest buildspec maintainers --breakdown** along with **buildtest rt --terse** , **buildtest buildspec find --terse**, **buildtest history list --terse** 

![image](https://user-images.githubusercontent.com/35829130/199876898-4d2a7925-a83c-409d-a50c-989f306bdf6c.png)

![image](https://user-images.githubusercontent.com/35829130/199877036-38cb670c-daf8-43cf-988d-248d7b2b969e.png)

![image](https://user-images.githubusercontent.com/35829130/199877163-243095a8-daf8-49ca-b299-702b169cb638.png)

![image](https://user-images.githubusercontent.com/35829130/199877271-fafca453-36a9-4254-b78b-39df24d7a067.png)

![image](https://user-images.githubusercontent.com/35829130/199877364-13eae747-fca8-412e-8433-8cac77efa9ae.png)

![image](https://user-images.githubusercontent.com/35829130/199877499-5833325f-bfaa-49b8-b6e5-1fcf391a9fea.png)

2022-11-04 18:33 UTC, shahzebsiddiqui commented on buildtest/cli/history.py
> +        t = [list(i) for i in zip(*join_list)]
perhaps use more meaningful variables for `t` i guess `transposed_list` i am not sure. For `join_list` perhaps use a different name perhaps `row_entry` or something i think that joined list is an entry or use a more meaningful name

2022-11-04 18:33 UTC, shahzebsiddiqui commented on buildtest/cli/history.py
> +        for i in t:
perhaps change `i` to something like `row` or `line`

2022-11-04 18:35 UTC, shahzebsiddiqui commented on buildtest/cli/report.py
>              for i in t:
same here perhaps use `row_entry` or `line` to indicate its a line

2022-11-04 18:36 UTC, shahzebsiddiqui commented on buildtest/cli/report.py
> +                join_string = "|".join(i)
rename this variable `join_string` perhaps `line` or `row_entry` or something else

2022-11-04 18:38 UTC, shahzebsiddiqui requested changes
a few minor changes to variable renaming.

2022-11-04 20:00 UTC, prathmesh4321 commented
> a few minor changes to variable renaming.

@shahzebsiddiqui Renamed the variables!

2022-11-07 18:39 UTC, shahzebsiddiqui approved these changes
thanks @prathmesh this looks better now

2022-11-07 18:39 UTC, merged