Assert Less Than for Status Check
buildtesters/buildtest pull request #1382
Opened 2023-02-09 19:19 UTC by Xiangs18

![pic](https://user-images.githubusercontent.com/22202096/217915505-891afe65-55a6-49f4-9307-9a57a627f3a0.JPG)

2023-02-09 19:30 UTC, shahzebsiddiqui commented
@prathmesh4321 can you please review

2023-02-09 19:56 UTC, prathmesh4321 requested changes
@Xiangs18 Can you also create a symlink in https://github.com/buildtesters/buildtest/tree/devel/tests/builders for the assert less than test in https://github.com/buildtesters/buildtest/tree/devel/tutorials/perf_checks if not done yet, so that the example test also gets tested. See https://github.com/buildtesters/buildtest/pull/1361 for reference.

2023-02-09 19:56 UTC, prathmesh4321 commented on buildtest/buildsystem/checks.py
> +    """Perform check on assert greater than when ``assert_lt`` is specified in buildspec. The return is a boolean value that determines if the check has passed.
Should be "Perform check on assert less than....."

2023-02-09 19:56 UTC, prathmesh4321 commented on buildtest/buildsystem/checks.py
> +    console.print(f"[blue]{builder}[/]: Greater Check: {bool_check}")
Should be Less than check.

2023-02-09 19:59 UTC, prathmesh4321 commented
> @prathmesh4321 can you please review

@shahzebsiddiqui Sure!

2023-02-10 01:10 UTC, Xiangs18 commented
Hey @prathmesh4321, updated!

2023-02-10 15:02 UTC, shahzebsiddiqui commented
thanks @Xiangs18 this looks good. thanks @prathmesh4321 for reviewing this. I resolved all threads. Merging this in 🚀

2023-02-10 15:03 UTC, merged