Test regex check Branch
buildtesters/buildtest pull request #1497
Opened 2023-06-22 23:40 UTC by szuananwar

Test_regex_check method add in ../test/builders/test_builders.py file
A symbolic link for ../../tutorials/test_status/status_regex.yml in test/builders

2023-06-23 13:22 UTC, shahzebsiddiqui commented
> Test_regex_check method add in ../test/builders/test_builders.py file A symbolic link for ../../tutorials/test_status/status_regex.yml in test/builders

Please take the time to write a description message instead of the auto-generated description from the commit message. 

Thanks.

2023-06-23 13:26 UTC, shahzebsiddiqui commented
@szuananwar can you please remove the `.idea` folder from the git commit. Please see https://github.com/buildtesters/buildtest/pull/1497/files. I think this comes up with PyCharm.  I think a better thing to do is put `.idea` in the top-level .gitignore so it automatically gets ignored. I looked at https://rider-support.jetbrains.com/hc/en-us/articles/207097529-What-is-the-idea-folder- to get an idea of what these files are. They are specific to PyCharm IDE editor for project settings

2023-06-23 13:29 UTC, shahzebsiddiqui commented on tests/builders/test_builders.py
> +    cmd.build()
this looks good. Take a look at https://app.codecov.io/gh/buildtesters/buildtest/pull/1497/blob/buildtest/buildsystem/checks.py 

In particular the missing coverage for the else statement. Can you please try to add coverage for this. You will want to create a custom buildspec and just simply run it or you can update the main `status_regex.yml`
![Screen Shot 2023-06-23 at 9 28 08 AM](https://github.com/buildtesters/buildtest/assets/12942230/45c6897a-a6e0-4300-a658-c20b91a27916)

2023-06-23 14:49 UTC, szuananwar commented
> > Test_regex_check method add in ../test/builders/test_builders.py file A symbolic link for ../../tutorials/test_status/status_regex.yml in test/builders
> 
> Please take the time to write a description message instead of the auto-generated description from the commit message.
> 
> Thanks.



> > Test_regex_check method add in ../test/builders/test_builders.py file A symbolic link for ../../tutorials/test_status/status_regex.yml in test/builders
> 
> Please take the time to write a description message instead of the auto-generated description from the commit message.
> 
> Thanks.

Changed, thanks!

2023-06-23 14:58 UTC, shahzebsiddiqui commented
@braeeast2001 please take a look at this PR it will help you address your assigned task

2023-06-23 15:01 UTC, shahzebsiddiqui commented
@szuananwar can you please run `buildtest style -a` or see the Style Check error message. 

You will want to make sure you have the precommit setup see https://buildtest.readthedocs.io/en/devel/contributing/code_contribution_guide.html#configuring-black-pre-commit-hook  
![Screen Shot 2023-06-23 at 10 59 29 AM](https://github.com/buildtesters/buildtest/assets/12942230/d570b90e-ca37-4f20-a877-fd5be77981e5)

For style check see https://buildtest.readthedocs.io/en/devel/contributing/code_contribution_guide.html#running-stylechecks-via-buildtest-stylecheck just simply run this command and it will work except for `pyflakes` which you need to do manually

2023-06-26 19:17 UTC, szuananwar commented
> @szuananwar can you please remove the `.idea` folder from the git commit. Please see https://github.com/buildtesters/buildtest/pull/1497/files. I think this comes up with PyCharm. I think a better thing to do is put `.idea` in the top-level .gitignore so it automatically gets ignored. I looked at https://rider-support.jetbrains.com/hc/en-us/articles/207097529-What-is-the-idea-folder- to get an idea of what these files are. They are specific to PyCharm IDE editor for project settings

Done!

2023-06-27 16:27 UTC, shahzebsiddiqui commented
@szuananwar can you please add `.idea` file to the top-level .gitignore so it is excluded

2023-06-29 13:45 UTC, shahzebsiddiqui requested changes
Thanks @szuananwar for addressing my previous remarks. I would like you to increase coverage by testing the case where its `stderr` see my message https://github.com/buildtesters/buildtest/pull/1497/files#r1239821776

2023-06-29 18:19 UTC, closed without merging