adding buildtest class
buildtesters/buildtest pull request #1503
Opened 2023-06-29 13:46 UTC by kingxleyy

2023-06-29 13:51 UTC, shahzebsiddiqui commented on tests/cli/test_build.py
> +                    profile=None,
why are you defining a `BuildTest` class this doesn't make sense. Just call the class and create an object

```python
cmd = Buildtest(...)
cmd.build()
```

2023-06-29 19:45 UTC, shahzebsiddiqui requested changes

2023-06-29 19:45 UTC, shahzebsiddiqui commented on tests/cli/test_build.py
> +        cmd = Buildtest(...)
i dont mean you literally copy the suggestion. The `...` was meant for you to fill the appropriate arguments to the class so you can invoke the BuildTest class. Please see examples from above. Once you are ready for review please ping me. In the meantime, i will mark this as a `Draft`

2023-07-05 20:06 UTC, Mendi03 commented
The regression test is not passing because there is no value for `buildspec_paths` for the code you added.

2023-07-05 21:41 UTC, Mendi03 requested changes
Check my comment on why the regression is failing. Furthermore, you still need to invoke the class **_with_** a value for `module` and `unload_modules`.

2023-07-05 21:41 UTC, Mendi03 commented on tests/cli/test_build.py
> +                buildspecs=[buildspec_paths],
The regression test is failing because the variable `buildspec_paths` is empty.

2023-07-06 21:14 UTC, Mendi03 commented on tests/cli/test_build.py
see my previous comment

2023-07-07 14:23 UTC, shahzebsiddiqui approved these changes

2023-07-07 14:23 UTC, merged