removed option --disable-executor-check from buildtest/cli/__init__.py
buildtesters/buildtest pull request #1541
Opened 2023-07-11 20:24 UTC by Mariamajib

2023-07-11 23:26 UTC, szuananwar reviewed
@Mariamajib Please see my comments.

2023-07-11 23:26 UTC, szuananwar commented on buildtest/cli/__init__.py
>      extra_group.add_argument(
Please remove lines from 672-676 as we discussed.

2023-07-11 23:26 UTC, szuananwar commented on bash_completion.sh
> +      local longoption="--buildspec --executor --executor-type --exclude --exclude-tags --filter --helpfilter --limit --maxpendtime --modules --module-purge --nodes --pollinterval --procs --profile -
This is correct, no more deletion needed.

2023-07-11 23:26 UTC, szuananwar commented on buildtest/config.py
This is correct, no more deletion needed.

2023-07-11 23:26 UTC, szuananwar commented on buildtest/main.py
This is correct, no more deletion needed.

2023-07-11 23:30 UTC, szuananwar commented
We will need to work on documenting these changes partner @Mariamajib! 
@shahzebsiddiqui right?

2023-07-11 23:36 UTC, shahzebsiddiqui commented
No this doesn't need to be documented we are removing this feature

2023-07-11 23:41 UTC, szuananwar commented
I meant remove it from the document  too: https://buildtest.readthedocs.io/en/devel/command.html#extra

2023-07-12 14:07 UTC, shahzebsiddiqui commented on buildtest/config.py
> +    def validate(self, moduletool=None):
can you also update the docstring there is line below that has 

```
validate_executors (bool): Check executor settings. This is the default behavior but can be disabled
```

2023-07-12 14:07 UTC, shahzebsiddiqui requested changes
please make this one change you should be all set

2023-07-12 17:46 UTC, shahzebsiddiqui commented
> @shahzebsiddiqui I meant remove it from the document too: https://buildtest.readthedocs.io/en/devel/command.html#extra

This is auto-generated so it will be removed, you could probably see it in the generated docs but right now they are not passing

2023-07-12 17:46 UTC, shahzebsiddiqui commented
@Mariamajib please fix the CI checks and documentation is not building

2023-07-12 19:28 UTC, Mariamajib commented
@szuananwar  I have removed lines from 672-676 as stated

2023-07-12 19:30 UTC, Mariamajib commented on buildtest/config.py
> +    def validate(self, moduletool=None):
> can you also update the docstring there is line below that has
> 
> ```
> validate_executors (bool): Check executor settings. This is the default behavior but can be disabled
> ```

@shahzebsiddiqui I have updated the docstring

2023-07-12 19:31 UTC, Mariamajib commented on buildtest/cli/__init__.py
>      extra_group.add_argument(
@szuananwar I have removed lines from 672-676 as stated

2023-07-12 19:45 UTC, shahzebsiddiqui commented
@Mariamajib i am seeing issues with regression test can you please take a look. Also documentation is not building

2023-07-12 19:47 UTC, shahzebsiddiqui commented
I did a quick search https://github.com/search?q=repo%3Abuildtesters%2Fbuildtest%20validate_executors&type=code and found a few more references to where we set `validate_executors=True`. Please fix this

2023-07-12 19:51 UTC, Mariamajib commented
@shahzebsiddiqui  Thank you. I will fix it!

2023-07-14 16:20 UTC, merged