add unique id as part of test directory.
buildtesters/buildtest pull request #281
Opened 2020-04-18 18:25 UTC by shahzebsiddiqui

This PR will create a unique uuid in test directory, this avoids having test written in same location during repetition, furthermore we can use uuid as part of test identification as part of reporting.

The uuid is invoked per test block so for instance a Buildspec [hello.yml](https://github.com/HPC-buildtest/tutorials/blob/master/apps/serial/hello.yml) has three test block, each one will have a unique uuid. This avoids any name conflicts with same test block or Buildspec name named across different directories. 

For now it was logical to invoke ``uuid.uuid4()`` at the time of getting test directory, if unique id was to be done earlier, we would have to define the uuid much earlier in the code and pass the variable to the appropriate class. This would seem a bit confusing if variable is declared in one class just so that it is used much later down the code.

```
(buildtest-framework) ssi29@ag-mxg-hulk090> buildtest build -b apps/serial/hello.yml

            Discovered Buildspecs

/mxg-hpc/users/ssi29/tutorials/apps/serial/hello.yml

Buildspec Name                 SubTest                        Status                         Buildspec Path
________________________________________________________________________________________________________________________
hello                          fortan_hello                   PASSED                         /mxg-hpc/users/ssi29/tutorials/apps/serial/hello.yml
hello                          c_hello                        PASSED                         /mxg-hpc/users/ssi29/tutorials/apps/serial/hello.yml
hello                          cplusplus_hello                PASSED                         /mxg-hpc/users/ssi29/tutorials/apps/serial/hello.yml

============================================================
                        Test summary
============================================================
Executed 3 tests
Passed Tests: 3/3 Percentage: 100.000%
Failed Tests: 0/3 Percentage: 0.000%

(buildtest-framework) ssi29@ag-mxg-hulk090> tree .buildtest/
.buildtest/
├── 28b58e56-2ec2-4020-a432-f73a0d601533
│   └── hello
│       ├── fortan_hello.sh
│       ├── hello_f90
│       └── run
│           ├── fortan_hello_04-18-2020-14-20.err
│           └── fortan_hello_04-18-2020-14-20.out
├── 2e104f9d-be1a-4cba-8647-a56eaa5b0b94
│   └── hello
│       ├── c_hello.sh
│       ├── hello_c
│       └── run
│           ├── c_hello_04-18-2020-14-20.err
│           └── c_hello_04-18-2020-14-20.out
└── a3c1750c-3ad4-4149-9a2a-ca610f1dc0ff
    └── hello
        ├── cplusplus_hello.sh
        ├── hello_cpp
        └── run
            ├── cplusplus_hello_04-18-2020-14-20.err
            └── cplusplus_hello_04-18-2020-14-20.out

9 directories, 12 files

```

2020-04-18 19:07 UTC, vsoch commented
If you are going to hide test results in this manner, it should at least be with something meaningful (e.g., a timestamp). This makes buildtest a lot harder to use, imho.

2020-04-18 19:08 UTC, vsoch requested changes
Subfolder needs a meaningful name, not just uuid.

2020-04-19 01:04 UTC, shahzebsiddiqui commented
> If you are going to hide test results in this manner, it should at least be with something meaningful (e.g., a timestamp). This makes buildtest a lot harder to use, imho.

I can see your point, having to ``cd`` into a long uuid is not nice. I want to use uuid somewhere maybe not in a sub-directory. I think it would be nice to have it reference as part of reporting feature. I can see kubernettes ``kubectl get pods <pod>`` Where pod has name + hash.

I think timestamp will result in same issues, it won't be intuitive ``cd`` by timestamp since it doesn't mean much. Do you want one sub-directory created per buildtest, Buildspec file, or each test block in buildspec. Currently I have it once per test block. 

Another option i had was to use a shorter uuid and merge with the existing name we have so add few chars (6-8) as a hash. So a dirname ``helloworld`` could have the name + some hash ``helloworld-ska2vaf4``.

What you think?

2020-04-19 01:11 UTC, shahzebsiddiqui commented
what about this layout

This is one per test block. It's taking the last 8 chars from uuid. 

```
(buildtest-framework) ssi29@ag-mxg-hulk090> ll .buildtest/
total 3
drwxr-xr-x 3 ssi29 hks 4096 Apr 18 21:10 disk_usage-1db45f3b
drwxr-xr-x 3 ssi29 hks 4096 Apr 18 21:10 selinux-ea9aca57
drwxr-xr-x 3 ssi29 hks 4096 Apr 18 21:10 systemd-6d027315
drwxr-xr-x 3 ssi29 hks 4096 Apr 18 21:10 ulimits-8e198a32
drwxr-xr-x 3 ssi29 hks 4096 Apr 18 21:10 ulimits-8fa55f22
drwxr-xr-x 3 ssi29 hks 4096 Apr 18 21:10 ulimits-ddee8e00

```

2020-04-19 01:33 UTC, vsoch commented
The structure that I like is snakemake. 

```
$ tree -L 2 .snakemake/
.snakemake/
├── conda
│   ├── 1e581ae6
│   ├── 1e581ae6.yaml
│   ├── 24f953d1
│   ├── 24f953d1.yaml
│   ├── 257f3909
│   ├── 257f3909.yaml
│   ├── 31fdb957
│   ├── 31fdb957.yaml
│   ├── 3cec026c
│   ├── 3cec026c.yaml
│   ├── 6806e217
│   ├── 6806e217.yaml
│   ├── a29f1e51
│   ├── a29f1e51.yaml
│   ├── cc2b908e
│   ├── cc2b908e.yaml
│   ├── fcebda9c
│   └── fcebda9c.yaml
├── conda-archive
├── locks
├── log
│   ├── 2020-03-11T164626.150479.snakemake.log
│   ├── 2020-03-11T164709.864478.snakemake.log
│   ├── 2020-03-11T164721.301653.snakemake.log
│   ├── 2020-03-11T164744.333489.snakemake.log
│   ├── 2020-03-11T164814.434434.snakemake.log
│   ├── 2020-03-11T164920.057777.snakemake.log
│   ├── 2020-03-11T164931.444699.snakemake.log
│   ├── 2020-03-11T165012.300239.snakemake.log
│   └── 2020-03-11T212136.521847.snakemake.log
├── metadata
├── shadow
└── singularity

16 directories, 18 files
```

The reasons are because:

 - the top level folders are meaningful - I cd and I know scripts are in scripts, logs in logs, etc., and everything is relevant to my current run.
 - it uses identifiers that are *meaningful* and not just randomly generated uuid for the sake of it (in the above, the logs are meaningful because I can match to dates and times). 
 - the only subfolders that aren't so interesting to the user (and I wouldn't commonly browse there) are the hashes for the conda environments. Only if I need to do some very detailed debugging would I see the logs to source an environment, and then do that (and they are organized as such).

You are adding a layer that makes it hard to see content because it's further nested, plus you are creating ids that aren't meaningful in any way. If you take a look at snakemake source code, you'll notice that files (and determining the cache) is totally based on meaningful content hashes. So if you want to do this right, the test should generate a hash that includes the test config _and_ the content files used for it, and then the result saved in a local .buildtest/cache (with that hash) so it doesn't need to be run again, unless the user species --no-cache or something like that. And for meaningful files that the user needs to find, we need a timestamp. 

Also missing from buidltest (that needs to be addressed) is a lock file for a current directory, so tests can only be run once at a time.

2020-04-19 15:58 UTC, shahzebsiddiqui commented
> The structure that I like is snakemake.
> 
> ```
> $ tree -L 2 .snakemake/
> .snakemake/
> ├── conda
> │   ├── 1e581ae6
> │   ├── 1e581ae6.yaml
> │   ├── 24f953d1
> │   ├── 24f953d1.yaml
> │   ├── 257f3909
> │   ├── 257f3909.yaml
> │   ├── 31fdb957
> │   ├── 31fdb957.yaml
> │   ├── 3cec026c
> │   ├── 3cec026c.yaml
> │   ├── 6806e217
> │   ├── 6806e217.yaml
> │   ├── a29f1e51
> │   ├── a29f1e51.yaml
> │   ├── cc2b908e
> │   ├── cc2b908e.yaml
> │   ├── fcebda9c
> │   └── fcebda9c.yaml
> ├── conda-archive
> ├── locks
> ├── log
> │   ├── 2020-03-11T164626.150479.snakemake.log
> │   ├── 2020-03-11T164709.864478.snakemake.log
> │   ├── 2020-03-11T164721.301653.snakemake.log
> │   ├── 2020-03-11T164744.333489.snakemake.log
> │   ├── 2020-03-11T164814.434434.snakemake.log
> │   ├── 2020-03-11T164920.057777.snakemake.log
> │   ├── 2020-03-11T164931.444699.snakemake.log
> │   ├── 2020-03-11T165012.300239.snakemake.log
> │   └── 2020-03-11T212136.521847.snakemake.log
> ├── metadata
> ├── shadow
> └── singularity
> 
> 16 directories, 18 files
> ```
> 
> The reasons are because:
> 
> * the top level folders are meaningful - I cd and I know scripts are in scripts, logs in logs, etc., and everything is relevant to my current run.
> * it uses identifiers that are _meaningful_ and not just randomly generated uuid for the sake of it (in the above, the logs are meaningful because I can match to dates and times).
> * the only subfolders that aren't so interesting to the user (and I wouldn't commonly browse there) are the hashes for the conda environments. Only if I need to do some very detailed debugging would I see the logs to source an environment, and then do that (and they are organized as such).
> 
> You are adding a layer that makes it hard to see content because it's further nested, plus you are creating ids that aren't meaningful in any way. If you take a look at snakemake source code, you'll notice that files (and determining the cache) is totally based on meaningful content hashes. So if you want to do this right, the test should generate a hash that includes the test config _and_ the content files used for it, and then the result saved in a local .buildtest/cache (with that hash) so it doesn't need to be run again, unless the user species --no-cache or something like that. And for meaningful files that the user needs to find, we need a timestamp.
> 
> Also missing from buidltest (that needs to be addressed) is a lock file for a current directory, so tests can only be run once at a time.

This may seem a lot more than i initially expected, so for time being i will revert my change back to original behavior and address the minor tweaks and let you propose the directory structure. I anticipate tests to be run periodically when it comes to acceptance testing so I am having hard time understanding what the lockfile will be used for in context of buildtest. If the lockfile is meant to prevent writing the testscript and proceed to just execution, I can see this would be useful.

2020-04-19 16:04 UTC, shahzebsiddiqui commented
closing this PR in response to #283.

2020-04-19 16:04 UTC, closed without merging